# Generated by Django 4.2.11 on 2024-04-22 16:54

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(default='', max_length=80, verbose_name='name')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('post', django_ckeditor_5.fields.CKEditor5Field(help_text='You can add shortcodes in the post e.g[[youtube #videoid# #caption#]], ')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.PositiveIntegerField(default=115),
        ),
    ]
